//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18010
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedisManagementStudio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point FFolderPosition {
            get {
                return ((global::System.Drawing.Point)(this["FFolderPosition"]));
            }
            set {
                this["FFolderPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("363, 393")]
        public global::System.Drawing.Size FFolderDimension {
            get {
                return ((global::System.Drawing.Size)(this["FFolderDimension"]));
            }
            set {
                this["FFolderDimension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point FConnexionPosition {
            get {
                return ((global::System.Drawing.Point)(this["FConnexionPosition"]));
            }
            set {
                this["FConnexionPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("434, 473")]
        public global::System.Drawing.Size FConnexionDimension {
            get {
                return ((global::System.Drawing.Size)(this["FConnexionDimension"]));
            }
            set {
                this["FConnexionDimension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point FImportExportPosition {
            get {
                return ((global::System.Drawing.Point)(this["FImportExportPosition"]));
            }
            set {
                this["FImportExportPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("498, 420")]
        public global::System.Drawing.Size FImportExportDimension {
            get {
                return ((global::System.Drawing.Size)(this["FImportExportDimension"]));
            }
            set {
                this["FImportExportDimension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point FRedisUtilPostion {
            get {
                return ((global::System.Drawing.Point)(this["FRedisUtilPostion"]));
            }
            set {
                this["FRedisUtilPostion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900, 460")]
        public global::System.Drawing.Size FRedisUtilDimension {
            get {
                return ((global::System.Drawing.Size)(this["FRedisUtilDimension"]));
            }
            set {
                this["FRedisUtilDimension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("155")]
        public int FRedisUtilSplit {
            get {
                return ((int)(this["FRedisUtilSplit"]));
            }
            set {
                this["FRedisUtilSplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int RedisListInfoUIColProperty {
            get {
                return ((int)(this["RedisListInfoUIColProperty"]));
            }
            set {
                this["RedisListInfoUIColProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int RedisListInfoUIColValue {
            get {
                return ((int)(this["RedisListInfoUIColValue"]));
            }
            set {
                this["RedisListInfoUIColValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280")]
        public int FRedisUtilClientListUISplit {
            get {
                return ((int)(this["FRedisUtilClientListUISplit"]));
            }
            set {
                this["FRedisUtilClientListUISplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280")]
        public int RedisClientListUISplit {
            get {
                return ((int)(this["RedisClientListUISplit"]));
            }
            set {
                this["RedisClientListUISplit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int RedisClientListUIColProperty {
            get {
                return ((int)(this["RedisClientListUIColProperty"]));
            }
            set {
                this["RedisClientListUIColProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int RedisClientListUIColValue {
            get {
                return ((int)(this["RedisClientListUIColValue"]));
            }
            set {
                this["RedisClientListUIColValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 300")]
        public global::System.Drawing.Point FManagementPosition {
            get {
                return ((global::System.Drawing.Point)(this["FManagementPosition"]));
            }
            set {
                this["FManagementPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 445")]
        public global::System.Drawing.Size FManagementDimension {
            get {
                return ((global::System.Drawing.Size)(this["FManagementDimension"]));
            }
            set {
                this["FManagementDimension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ColWidthEditHashKey {
            get {
                return ((int)(this["ColWidthEditHashKey"]));
            }
            set {
                this["ColWidthEditHashKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ColWidthEditHashValue {
            get {
                return ((int)(this["ColWidthEditHashValue"]));
            }
            set {
                this["ColWidthEditHashValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ColWidthEditHashNew {
            get {
                return ((int)(this["ColWidthEditHashNew"]));
            }
            set {
                this["ColWidthEditHashNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ColWidthEditTextKey {
            get {
                return ((int)(this["ColWidthEditTextKey"]));
            }
            set {
                this["ColWidthEditTextKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ColWidthEditTextValue {
            get {
                return ((int)(this["ColWidthEditTextValue"]));
            }
            set {
                this["ColWidthEditTextValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ColWidthEditZSetMembre {
            get {
                return ((int)(this["ColWidthEditZSetMembre"]));
            }
            set {
                this["ColWidthEditZSetMembre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ColWidthEditZSetScore {
            get {
                return ((int)(this["ColWidthEditZSetScore"]));
            }
            set {
                this["ColWidthEditZSetScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ColWidthEditZSetNew {
            get {
                return ((int)(this["ColWidthEditZSetNew"]));
            }
            set {
                this["ColWidthEditZSetNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 150")]
        public global::System.Drawing.Point FManageInfoPosition {
            get {
                return ((global::System.Drawing.Point)(this["FManageInfoPosition"]));
            }
            set {
                this["FManageInfoPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700, 450")]
        public global::System.Drawing.Size FManageInfoDimensions {
            get {
                return ((global::System.Drawing.Size)(this["FManageInfoDimensions"]));
            }
            set {
                this["FManageInfoDimensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int FManageInfoSpliter {
            get {
                return ((int)(this["FManageInfoSpliter"]));
            }
            set {
                this["FManageInfoSpliter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ColManageCommand {
            get {
                return ((int)(this["ColManageCommand"]));
            }
            set {
                this["ColManageCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ColManageCode {
            get {
                return ((int)(this["ColManageCode"]));
            }
            set {
                this["ColManageCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ColManageTypeAlarm {
            get {
                return ((int)(this["ColManageTypeAlarm"]));
            }
            set {
                this["ColManageTypeAlarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int ColManageTitre {
            get {
                return ((int)(this["ColManageTitre"]));
            }
            set {
                this["ColManageTitre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int KeySearchDisplayMode {
            get {
                return ((int)(this["KeySearchDisplayMode"]));
            }
            set {
                this["KeySearchDisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int ColWidthMonitorDate {
            get {
                return ((int)(this["ColWidthMonitorDate"]));
            }
            set {
                this["ColWidthMonitorDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ColWidthMonitorIp {
            get {
                return ((int)(this["ColWidthMonitorIp"]));
            }
            set {
                this["ColWidthMonitorIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ColWidthMonitorCommand {
            get {
                return ((int)(this["ColWidthMonitorCommand"]));
            }
            set {
                this["ColWidthMonitorCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonitorConsoleScroll {
            get {
                return ((bool)(this["MonitorConsoleScroll"]));
            }
            set {
                this["MonitorConsoleScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MonitorConsoleSaveFileName {
            get {
                return ((string)(this["MonitorConsoleSaveFileName"]));
            }
            set {
                this["MonitorConsoleSaveFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeySearchDisplayMelangeType {
            get {
                return ((bool)(this["KeySearchDisplayMelangeType"]));
            }
            set {
                this["KeySearchDisplayMelangeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int ColWidthPubSubDate {
            get {
                return ((int)(this["ColWidthPubSubDate"]));
            }
            set {
                this["ColWidthPubSubDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ColWidthPubSubAction {
            get {
                return ((int)(this["ColWidthPubSubAction"]));
            }
            set {
                this["ColWidthPubSubAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ColWidthPubSubPattern {
            get {
                return ((int)(this["ColWidthPubSubPattern"]));
            }
            set {
                this["ColWidthPubSubPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ColWidthPubSubChanel {
            get {
                return ((int)(this["ColWidthPubSubChanel"]));
            }
            set {
                this["ColWidthPubSubChanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ColWidthPubSubMessage {
            get {
                return ((int)(this["ColWidthPubSubMessage"]));
            }
            set {
                this["ColWidthPubSubMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point FAddKeyLocation {
            get {
                return ((global::System.Drawing.Point)(this["FAddKeyLocation"]));
            }
            set {
                this["FAddKeyLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("347, 254")]
        public global::System.Drawing.Size FAddKeyDimension {
            get {
                return ((global::System.Drawing.Size)(this["FAddKeyDimension"]));
            }
            set {
                this["FAddKeyDimension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ColWidthMonitorBase {
            get {
                return ((int)(this["ColWidthMonitorBase"]));
            }
            set {
                this["ColWidthMonitorBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ColWidthMonitorPort {
            get {
                return ((int)(this["ColWidthMonitorPort"]));
            }
            set {
                this["ColWidthMonitorPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int KeySearchNombreMinChar {
            get {
                return ((int)(this["KeySearchNombreMinChar"]));
            }
            set {
                this["KeySearchNombreMinChar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int KeyGroupColCle {
            get {
                return ((int)(this["KeyGroupColCle"]));
            }
            set {
                this["KeyGroupColCle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int KeyGroupColType {
            get {
                return ((int)(this["KeyGroupColType"]));
            }
            set {
                this["KeyGroupColType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ColWidthSentinelServersProperty {
            get {
                return ((int)(this["ColWidthSentinelServersProperty"]));
            }
            set {
                this["ColWidthSentinelServersProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int ColWidthSentinelServersValue {
            get {
                return ((int)(this["ColWidthSentinelServersValue"]));
            }
            set {
                this["ColWidthSentinelServersValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("410")]
        public int SentinelServersSplitter {
            get {
                return ((int)(this["SentinelServersSplitter"]));
            }
            set {
                this["SentinelServersSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 100")]
        public global::System.Drawing.Point FRenamePosition {
            get {
                return ((global::System.Drawing.Point)(this["FRenamePosition"]));
            }
            set {
                this["FRenamePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 165")]
        public global::System.Drawing.Size FRenameDimension {
            get {
                return ((global::System.Drawing.Size)(this["FRenameDimension"]));
            }
            set {
                this["FRenameDimension"] = value;
            }
        }
    }
}
