//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18010
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedisManagementStudio.BLL.Redis {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class Rubrique {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rubrique() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedisManagementStudio.BLL.Redis.Rubrique", typeof(Rubrique).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toutes rubriques.
        /// </summary>
        internal static string CmdInfoRubriqueAllRubrique {
            get {
                return ResourceManager.GetString("CmdInfoRubriqueAllRubrique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clients.
        /// </summary>
        internal static string CmdInfoRubriqueClient {
            get {
                return ResourceManager.GetString("CmdInfoRubriqueClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commandes.
        /// </summary>
        internal static string CmdInfoRubriqueCommand {
            get {
                return ResourceManager.GetString("CmdInfoRubriqueCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        internal static string CmdInfoRubriqueConfiguration {
            get {
                return ResourceManager.GetString("CmdInfoRubriqueConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mémoire &amp; Processeur.
        /// </summary>
        internal static string CmdInfoRubriqueMemoryCPU {
            get {
                return ResourceManager.GetString("CmdInfoRubriqueMemoryCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non affiché.
        /// </summary>
        internal static string CmdInfoRubriqueNone {
            get {
                return ResourceManager.GetString("CmdInfoRubriqueNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde .
        /// </summary>
        internal static string CmdInfoRubriquePersistance {
            get {
                return ResourceManager.GetString("CmdInfoRubriquePersistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement en cours....
        /// </summary>
        internal static string CmdInfoRubriquePersistanceLoading {
            get {
                return ResourceManager.GetString("CmdInfoRubriquePersistanceLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réplication &amp; Cluster.
        /// </summary>
        internal static string CmdInfoRubriqueReplication {
            get {
                return ResourceManager.GetString("CmdInfoRubriqueReplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sentinel.
        /// </summary>
        internal static string CmdInfoRubriqueSentinel {
            get {
                return ResourceManager.GetString("CmdInfoRubriqueSentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Serveur.
        /// </summary>
        internal static string CmdInfoRubriqueServer {
            get {
                return ResourceManager.GetString("CmdInfoRubriqueServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistiques.
        /// </summary>
        internal static string CmdInfoRubriqueStatistics {
            get {
                return ResourceManager.GetString("CmdInfoRubriqueStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inconnus.
        /// </summary>
        internal static string CmdInfoRubriqueUnKnow {
            get {
                return ResourceManager.GetString("CmdInfoRubriqueUnKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regrouppement de clés.
        /// </summary>
        internal static string ETypeKeyFolderD {
            get {
                return ResourceManager.GetString("ETypeKeyFolderD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Regrouppement.
        /// </summary>
        internal static string ETypeKeyFolderT {
            get {
                return ResourceManager.GetString("ETypeKeyFolderT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dictionnaire : Ensemble de Clés / Valeurs, permet de représenter des objets sous la forme propriété valeur..
        /// </summary>
        internal static string ETypeKeyThashD {
            get {
                return ResourceManager.GetString("ETypeKeyThashD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à de type disctionnaire.
        /// </summary>
        internal static string ETypeKeyThashF {
            get {
                return ResourceManager.GetString("ETypeKeyThashF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dictionnaire.
        /// </summary>
        internal static string ETypeKeyThashT {
            get {
                return ResourceManager.GetString("ETypeKeyThashT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste : une liste permet d&apos;enregistrer des chaines et d&apos;y accéder par un index. Elle est trié dans l&apos;ordre d&apos;insertion. On peut y ajouter des valeur par l&apos;entête ou la fin de la liste..
        /// </summary>
        internal static string ETypeKeyTlistD {
            get {
                return ResourceManager.GetString("ETypeKeyTlistD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à de type liste.
        /// </summary>
        internal static string ETypeKeyTlistF {
            get {
                return ResourceManager.GetString("ETypeKeyTlistF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste.
        /// </summary>
        internal static string ETypeKeyTlistT {
            get {
                return ResourceManager.GetString("ETypeKeyTlistT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun : La clé a été supprimé après le dernier rafraichissement de l&apos;écran..
        /// </summary>
        internal static string ETypeKeyTnoneD {
            get {
                return ResourceManager.GetString("ETypeKeyTnoneD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string ETypeKeyTnoneF {
            get {
                return ResourceManager.GetString("ETypeKeyTnoneF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun : clé inconnue.
        /// </summary>
        internal static string ETypeKeyTnoneT {
            get {
                return ResourceManager.GetString("ETypeKeyTnoneT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set : Ensemble de valeurs non ordonnées et uniques. Lorsque l&apos;on ajoute une valeur à un Set si celle ci exiiste déjà cela n&apos;a aucun effet..
        /// </summary>
        internal static string ETypeKeyTsetD {
            get {
                return ResourceManager.GetString("ETypeKeyTsetD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à de type Set.
        /// </summary>
        internal static string ETypeKeyTsetF {
            get {
                return ResourceManager.GetString("ETypeKeyTsetF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set.
        /// </summary>
        internal static string ETypeKeyTsetT {
            get {
                return ResourceManager.GetString("ETypeKeyTsetT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chaîne : Représente un tableau de Bytes. Permet de stoquer des chaines diverses, des nombres, des vecteurs de booléens..
        /// </summary>
        internal static string ETypeKeyTstringD {
            get {
                return ResourceManager.GetString("ETypeKeyTstringD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à de type chaîne.
        /// </summary>
        internal static string ETypeKeyTstringF {
            get {
                return ResourceManager.GetString("ETypeKeyTstringF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chaîne.
        /// </summary>
        internal static string ETypeKeyTstringT {
            get {
                return ResourceManager.GetString("ETypeKeyTstringT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set trié : Ensemble de valeurs associées à un score, chaque valeur est unique dans le set, et les valeurs sont classé par ordre des scores..
        /// </summary>
        internal static string ETypeKeyTzsetD {
            get {
                return ResourceManager.GetString("ETypeKeyTzsetD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à de type set trié.
        /// </summary>
        internal static string ETypeKeyTzsetF {
            get {
                return ResourceManager.GetString("ETypeKeyTzsetF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set trié.
        /// </summary>
        internal static string ETypeKeyTzsetT {
            get {
                return ResourceManager.GetString("ETypeKeyTzsetT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non connu Desc.
        /// </summary>
        internal static string ETypeKeyUnKnowD {
            get {
                return ResourceManager.GetString("ETypeKeyUnKnowD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à de tous types.
        /// </summary>
        internal static string ETypeKeyUnKnowF {
            get {
                return ResourceManager.GetString("ETypeKeyUnKnowF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Tous].
        /// </summary>
        internal static string ETypeKeyUnKnowR {
            get {
                return ResourceManager.GetString("ETypeKeyUnKnowR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non connu.
        /// </summary>
        internal static string ETypeKeyUnKnowT {
            get {
                return ResourceManager.GetString("ETypeKeyUnKnowT", resourceCulture);
            }
        }
    }
}
