//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18010
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedisManagementStudio.BLL {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedisManagementStudio.BLL.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visualisation de gestion des clients connecté au serveur.
        /// </summary>
        internal static string CommandMenuActionClientsD {
            get {
                return ResourceManager.GetString("CommandMenuActionClientsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clients.
        /// </summary>
        internal static string CommandMenuActionClientsT {
            get {
                return ResourceManager.GetString("CommandMenuActionClientsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visualisation et configuration des paramètres du serveur.
        /// </summary>
        internal static string CommandMenuActionConfigurationD {
            get {
                return ResourceManager.GetString("CommandMenuActionConfigurationD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visualisation et configuration des paramètres du serveur.
        /// </summary>
        internal static string CommandMenuActionConfigurationRubriqueD {
            get {
                return ResourceManager.GetString("CommandMenuActionConfigurationRubriqueD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        internal static string CommandMenuActionConfigurationRubriqueT {
            get {
                return ResourceManager.GetString("CommandMenuActionConfigurationRubriqueT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        internal static string CommandMenuActionConfigurationT {
            get {
                return ResourceManager.GetString("CommandMenuActionConfigurationT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Explorateur des données du serveur.
        /// </summary>
        internal static string CommandMenuActionKeysD {
            get {
                return ResourceManager.GetString("CommandMenuActionKeysD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Données.
        /// </summary>
        internal static string CommandMenuActionKeysT {
            get {
                return ResourceManager.GetString("CommandMenuActionKeysT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir la trace des commandes sur le serveur.
        /// </summary>
        internal static string CommandMenuActionMonitorD {
            get {
                return ResourceManager.GetString("CommandMenuActionMonitorD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trace.
        /// </summary>
        internal static string CommandMenuActionMonitorT {
            get {
                return ResourceManager.GetString("CommandMenuActionMonitorT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;abonner aux cannaux pour recevoir des messages.
        /// </summary>
        internal static string CommandMenuActionPubSubAbonnementD {
            get {
                return ResourceManager.GetString("CommandMenuActionPubSubAbonnementD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abonnement.
        /// </summary>
        internal static string CommandMenuActionPubSubAbonnementT {
            get {
                return ResourceManager.GetString("CommandMenuActionPubSubAbonnementT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Diffuser des messages ou s&apos;abonner à des canaux.
        /// </summary>
        internal static string CommandMenuActionPubSubD {
            get {
                return ResourceManager.GetString("CommandMenuActionPubSubD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Messages : Diffusion / Abonnements.
        /// </summary>
        internal static string CommandMenuActionPubSubT {
            get {
                return ResourceManager.GetString("CommandMenuActionPubSubT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les serveurs suivis par Sentinel.
        /// </summary>
        internal static string CommandMenuActionSentinelServersD {
            get {
                return ResourceManager.GetString("CommandMenuActionSentinelServersD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Serveurs suivis.
        /// </summary>
        internal static string CommandMenuActionSentinelServersT {
            get {
                return ResourceManager.GetString("CommandMenuActionSentinelServersT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détail des propriétés du serveur.
        /// </summary>
        internal static string CommandMenuActionServerD {
            get {
                return ResourceManager.GetString("CommandMenuActionServerD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Propriétés du serveur.
        /// </summary>
        internal static string CommandMenuActionServerT {
            get {
                return ResourceManager.GetString("CommandMenuActionServerT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boite à outils..
        /// </summary>
        internal static string CommandMenuActionToolsD {
            get {
                return ResourceManager.GetString("CommandMenuActionToolsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outils.
        /// </summary>
        internal static string CommandMenuActionToolsT {
            get {
                return ResourceManager.GetString("CommandMenuActionToolsT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 heure.
        /// </summary>
        internal static string TimeSpan1Heure {
            get {
                return ResourceManager.GetString("TimeSpan1Heure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 jour.
        /// </summary>
        internal static string TimeSpan1jour {
            get {
                return ResourceManager.GetString("TimeSpan1jour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 milliseconde.
        /// </summary>
        internal static string TimeSpan1MilliSeconde {
            get {
                return ResourceManager.GetString("TimeSpan1MilliSeconde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 minute.
        /// </summary>
        internal static string TimeSpan1Minute {
            get {
                return ResourceManager.GetString("TimeSpan1Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 seconde.
        /// </summary>
        internal static string TimeSpan1Seconde {
            get {
                return ResourceManager.GetString("TimeSpan1Seconde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} heures.
        /// </summary>
        internal static string TimeSpanNHeure {
            get {
                return ResourceManager.GetString("TimeSpanNHeure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} jours.
        /// </summary>
        internal static string TimeSpanNjour {
            get {
                return ResourceManager.GetString("TimeSpanNjour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} millisecondes.
        /// </summary>
        internal static string TimeSpanNMilliSeconde {
            get {
                return ResourceManager.GetString("TimeSpanNMilliSeconde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} minutes.
        /// </summary>
        internal static string TimeSpanNMinute {
            get {
                return ResourceManager.GetString("TimeSpanNMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} secondes.
        /// </summary>
        internal static string TimeSpanNSeconde {
            get {
                return ResourceManager.GetString("TimeSpanNSeconde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0:N3} millisecondes.
        /// </summary>
        internal static string TimeSpanNxMilliSecondes {
            get {
                return ResourceManager.GetString("TimeSpanNxMilliSecondes", resourceCulture);
            }
        }
    }
}
